version: '3'

services:
  zookeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLEINT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ['CMD','bash', '-c', "echo 'ruok' | nc localhost 2181"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - confluent

  broker:
    image: confluentinc/cp-server:7.4.0
    hostname: broker
    container_name: broker
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFA_BROKER_ID: 1
      KAFA_ZOOKEPER_CONNECT: 'zookeeper:2181'
      KAFA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://broker:9092
      KAFA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFA_OFFSETS_TOPIC_REPILCATION_FACTOR: 1
      KAFA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFA_CONFLUENT_LICENSE_TOPIC_REPILCATION_FACTOR: 1
      KAFA_CONFLUENT_BALANCER_TOPIC_REPILCATION_FACTOR: 1
      KAFA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFA_TRANSACTION_STATE_LOG_REPILCATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_REGISTRY_URL: http://schema_registry:8081
      CONFLUENT_METRICS_REPORTER_BOOSTSTRAP_SERVERS: BROKER:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'false'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  schema-registry:
    image: confluentinc/cp-server:7.4.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      broker:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSRAP_SERVERS: 'broker:29092'
      SCHEMA_REGISTRY_LISTERNERS: https://0.0.0.0:8081
    networks:
      - confluent
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8081']
      interval: 30s
      timeout: 10s
      retries: 5

  control-center:
    image: confluentinc/cp-server:7.4.0
    hostname: control-center
    container_name: control-center
    depends_on:
      broker:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    environment:
      CONTROL_CENTER_BOOSTRAP_SERVERS: 'broker:29092'
      CONTROL_CENTER_SCHEMA_URL: 'http://schema-registry:8081'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPICS_REPLICATION: 1
      CONFLUENT_METRICS_ENABLE: 'false'
      PORT: 9021
    networks:
      - confluent
networks:
  confluent:





